### ISSUE TITLE
Stuck in UEFI Interactive Shell after language prompt. (No mapping found)

### ISSUE THREAD

**Issue by Gangster8192** [myspaghetti/macos-guest-virtualbox#121] opened 2019-11-12 02:00 UTC
The script goes well util it boots macOS up for the first time. It asks for me to press enter when i reach the language screen, but I get "No mapping found" and then the uefi shell opens up. 
![image](https://user-images.githubusercontent.com/30675315/68635198-c5b0fb00-04c5-11ea-834f-24fd8fe64320.png)
This isn't limited to High Sierra, the version I attempted to try, this also happened for me in Mojave.

**Comment by Gangster8192** [comment] 2019-11-12 02:15
I'm also on Windows 10 (build 17763) and using WSL to install this, if it matters.

**Comment by Gangster8192** [comment] 2019-11-12 02:46
Here's the output of my WSL (Ubuntu 18 LTS)
[log.txt](https://github.com/myspaghetti/macos-guest-virtualbox/files/3834139/log.txt)

**Comment by myspaghetti** [comment] 2019-11-12 08:55
Thanks for the log.  This is a duplicate of [issue 83](https://github.com/myspaghetti/macos-guest-virtualbox/issues/83)

```
The script requires Windows 10 version 1903 or higher to run properly on WSL.
For lower versions, please run the script on a path on the Windows filesystem,
for example  /mnt/c/Users/Public/Documents
```

**Closed by myspaghetti** 2019-11-12 08:55 UTC
Labels: duplicate
