### ISSUE TITLE
AMD host support needs extra steps

### ISSUE THREAD

**Issue by athwds** [myspaghetti/macos-guest-virtualbox#85] opened 2019-07-20 16:25 UTC
I had to manually run these commands to get this working in an AMD host:

```
cd "C:\Program Files\Oracle\VirtualBox\"
VBoxManage.exe modifyvm "Your VM Name" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
VBoxManage setextradata "Your VM Name" "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "iMac11,3"
VBoxManage setextradata "Your VM Name" "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0"
VBoxManage setextradata "Your VM Name" "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Iloveapple"
VBoxManage setextradata "Your VM Name" "VBoxInternal/Devices/smc/0/Config/DeviceKey" "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
VBoxManage setextradata "Your VM Name" "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1
```

**Comment by myspaghetti** [comment] 2019-07-20 21:55
Duplicate of [issue 8](https://github.com/myspaghetti/macos-guest-virtualbox/issues/8)

**Closed by myspaghetti** 2019-07-20 21:55 UTC
Labels: duplicate
