### ISSUE TITLE
/sbin/newfs_hfs failed with error 256 (resource busy)

### ISSUE THREAD

**Issue by Taliyah-KOC** [myspaghetti/macos-guest-virtualbox#128] opened 2019-11-21 05:52 UTC
On a new install of Mojave using the latest released script, macOS terminal returns a 256 error when restoring the basesystem to /Volumes/Install
Seems it cannot create a filesystem on /dev/rdisk2s2 because the resource is busy,

Any help would be appreciated.
Using latest Virtualbox on Manarjo.

minor edit: I haven't stopped or restarted the install in any way so I still have the bash terminal open within the macOS VM. Would be a good time to try anything inside otherwise restarting it would break it even more.

**Comment by myspaghetti** [comment] 2019-11-21 14:35
If you still have Terminal open in the VM, you can upload its output.
click on the open Terminal

**Comment by myspaghetti** [comment] 2019-11-21 14:40
If you still have Terminal open in the VM, you can upload its output.

- Click on the open Terminal
- Scroll up (for example with PgUp) until you reach the top
- Click on the beginning of the text to select it and keep the button down while you drag the selection to the bottom
- Press Command+C or Super+C or Win+C to copy the text
- Type `curl -F 'f:1=`
- Press Command+V or Super+V or Win+V to paste the text
- Type `' ix.io` and press enter
- Post the resulting URL here

**Comment by Taliyah-KOC** [comment] 2019-11-21 15:14
Hi. Seems I can't reproduce it after going to sleep but I haven't changed the script in anyway other change storagesize to 35000 from the default 25000

Here's the output
http://ix.io/22qU

**Comment by myspaghetti** [comment] 2019-11-21 15:27
Looks like either a VirtualBox issue or read/write issues on the host. Have you experienced any issues with other VirtualBox virtual machine disks?

**Comment by Taliyah-KOC** [comment] 2019-11-21 15:35
No I haven't.
Although I just ran `-bash-3.2# asr restore --source "/Volumes/Mojav-files/BaseSystem.dmg" --target /Volumes/Install --erase --noprompt` again and it did result in the 256 error has mentioned originally.
http://ix.io/22r2
Is the script(or me maybe) doing anything wrong? This does happen when I don't edit the script too.

**Comment by myspaghetti** [comment] 2019-11-21 15:56
These are the checksums of `http://swcdn.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/Mojave_BaseSystem.dmg`:
```
md5sum b10c7482b32c747283536f29d1c4b9ca *Mojave_BaseSystem.dmg
sha1sum 9edeca7dad45ef7722cc67cf2678cafaa1ecc754 *Mojave_BaseSystem.dmg
sha256sum dbd28bbb48cb248989c6b48f57b464269fcb88a40745ce5683cb4f58321b6f31 *Mojave_BaseSystem.dmg
```
You should check any of them on the host, and possibly check the md5sum on the guest with `md5 /Volumes/Mojav-files/BaseSystem.dmg`
If the file is damaged the checksums will be different.

**Comment by myspaghetti** [comment] 2019-11-21 15:56
These are the checksums of `http://swcdn.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/BaseSystem.dmg`:
```
md5sum b10c7482b32c747283536f29d1c4b9ca *Mojave_BaseSystem.dmg
sha1sum 9edeca7dad45ef7722cc67cf2678cafaa1ecc754 *Mojave_BaseSystem.dmg
sha256sum dbd28bbb48cb248989c6b48f57b464269fcb88a40745ce5683cb4f58321b6f31 *Mojave_BaseSystem.dmg
```
You should check any of them on the host, and possibly check the md5sum on the guest with `md5 /Volumes/Mojav-files/BaseSystem.dmg`
If the file is damaged the checksums will be different.

**Comment by Taliyah-KOC** [comment] 2019-11-21 16:15
Seems to be a wild goose chase.
http://ix.io/22rk guest reports md5 is good
http://ix.io/22rj host reports md5 is good

**Comment by myspaghetti** [comment] 2019-11-21 16:28
Either VirtualBox has permission or read/write issues with the VDIs on the host, or the host has filesystem or disk issues, or something else. Either way I won't be able to debug this. Check any system logs for disk issues, check any anti-malware logs for events related to the VDI, or just give up. Since you're running Linux you might as well install macOS on QEMU/KVM.

**Comment by myspaghetti** [comment] 2019-11-21 16:32
You could try changing line `494` from `--variant standard 2>/dev/tty` to `--variant fixed 2>/dev/tty`
It might work around the issue.

Another possibility is that your host's storage is full.

**Comment by Taliyah-KOC** [comment] 2019-11-21 16:43
Host storage has 67GB free. Not even close to hitting storage limits. Could try KVM/QEMU. Will also try changing `494`
VirtualBox doesn't have issues reading/writing as I've had a previous Debian VM run just fine. This is specific to just macOS.

**Comment by myspaghetti** [comment] 2019-11-28 01:35
Closing until further details are provided.

**Comment by PatrickG** [comment] 2020-03-02 00:15
Hi, I have a similar error when trying to install Catalina using wsl 1.

The md5sum of /Volumes/Catal-files/BaseSystem.dmg (inside the vm) and Catalina_BaseSystem.dmg (wsl and cmd.exe) is f11ef5efd12ce36b77c6cee0cccd7d41.

![image](https://user-images.githubusercontent.com/196478/75636836-75031080-5c22-11ea-97c4-642a14059bf8.png)

![image](https://user-images.githubusercontent.com/196478/75636842-7b918800-5c22-11ea-81db-3533e2c8d307.png)

![image](https://user-images.githubusercontent.com/196478/75636848-83e9c300-5c22-11ea-89cd-5c7aa1861313.png)

**Comment by myspaghetti** [comment] 2020-03-02 00:29
Hi @PatrickG, the `md5sum` is correct. Try running the stage `populate_virtual_disks` again, seemed to work for Taliyah-KOC.

**Comment by PatrickG** [comment] 2020-03-02 00:43
If I CTRL-C and run `./macos-guest-virtualbox.sh populate_virtual_disks` i get this error:
```
stage: populate_virtual_disks
One or more virtual storage files could not be loaded. Exiting.
```

**Comment by myspaghetti** [comment] 2020-03-02 00:48
@PatrickG could you check which virtual storage devices are attached to the virtual machine? You can view them in the VirtualBox manager GUI or with `VBoxManage.exe showvminfo ${vm_name} | grep SATA` (if you have `grep` installed)

**Comment by PatrickG** [comment] 2020-03-02 00:50
```
Storage Controller Name (0):            SATA
SATA (0, 0): D:\macOS\macOS.vdi (UUID: e9fb44a9-608d-409f-9fee-8d7afb23e54a)
SATA (1, 0): D:\macOS\Install Catalina.vdi (UUID: 6c9ed3af-1783-4372-9a47-52a377c68602)
SATA (2, 0): D:\macOS\Catalina_BaseSystem.vdi (UUID: 1f89dc7b-adba-428f-a27c-59031b650910)
SATA (3, 0): D:\macOS\Catalina_Installation_files.viso (UUID: 3ea61e67-45d5-431e-bcc1-f1ba24aabd45)
```

**Comment by PatrickG** [comment] 2020-03-02 00:54
I need to say, that I've VirtualBox installed in D:\Program Files\Oracle\VirtualBox instead of C.
But I already changed line 180 to `cmd_path_VBoxManage='D:\Program Files\Oracle\VirtualBox\VBoxManage.exe'` and line 221 to `wsl_path_VBoxManage='/mnt/d/Program Files/Oracle/VirtualBox/VBoxManage.exe'`.

**Comment by myspaghetti** [comment] 2020-03-02 00:56
All the storage devices are attached, the script shouldn't report an error. I'll try to reproduce the issue.

**Comment by myspaghetti** [comment] 2020-03-02 01:00
Sorry for the question, but just to make sure, the virtual machine was powered off when you ran `./macos-guest-virtualbox.sh populate_virtual_disks`?

**Comment by PatrickG** [comment] 2020-03-02 01:00
I think the error occurred because the VM was still running.

**Comment by PatrickG** [comment] 2020-03-02 01:04
I got the same error (resource busy).

**Comment by myspaghetti** [comment] 2020-03-02 01:09
I'll try to reproduce the issue.

**Comment by myspaghetti** [comment] 2020-03-14 12:51
Marked issue #173 as duplicate. That issue results in the error message `Error: -69888: Couldn't unmount disk`

@JGithub56 just to make sure, what is the output when you execute the following command in the virtual machine Terminal?

```
diskutil list | grep "GB *disk"
```
The output should be as follows:
```
   0:                                                   *12.6 GB    disk0
   0:                                                   *83.9 GB    disk1
   0:      GUID_partition_scheme                        *2.1 GB     disk2
   1:                  Apple_HFS OS X Base System        2.0 GB     disk2s1
   0:                            HighS-files            *5.2 GB     disk3
```
Although the names of disk0, disk1, disk2, etc might be swapped, and "HighS-files" might be "Mojav-files" or "Catal-files".

**Comment by JGithub56** [comment] 2020-03-14 14:29
> Marked issue #173 as duplicate. That issue results in the error message `Error: -69888: Couldn't unmount disk`
> 
> @JGithub56 just to make sure, what is the output when you execute the following command in the virtual machine Terminal?
> 
> ```
> diskutil list | grep "GB *disk"
> ```
> 
> The output should be as follows:
> 
> ```
>    0:                                                   *12.6 GB    disk0
>    0:                                                   *83.9 GB    disk1
>    0:      GUID_partition_scheme                        *2.1 GB     disk2
>    1:                  Apple_HFS OS X Base System        2.0 GB     disk2s1
>    0:                            HighS-files            *5.2 GB     disk3
> ```
> 
> Although the names of disk0, disk1, disk2, etc might be swapped, and "HighS-files" might be "Mojav-files" or "Catal-files".

I have this in output:

![output-1](https://user-images.githubusercontent.com/62147746/76683550-4a8f5b00-6605-11ea-999e-4fda52e58458.png)

**Comment by myspaghetti** [comment] 2020-03-14 15:20
@JGithub56 that means the install volume is already formatted. Delete the install VDI and the target VDI and start the script again.

**Comment by JGithub56** [comment] 2020-03-14 16:07
Since i have deleted these files, the VM do not start, there is an error in the script 
![deltevdi](https://user-images.githubusercontent.com/62147746/76685620-7f0b1300-6615-11ea-96a0-8224f44e9dbf.png)
the VM start and stop at the same time.
If I start the VM in virtualbox manualy it writes:

![echec](https://user-images.githubusercontent.com/62147746/76685733-4881c800-6616-11ea-88d7-1645a14799e6.png)

**Comment by myspaghetti** [comment] 2020-03-14 17:00
Delete them from the VirtualBox media manager too.

**Comment by JGithub56** [comment] 2020-03-14 18:33
it seems to come to the end, but I still have some errors as below

![end](https://user-images.githubusercontent.com/62147746/76688156-b33cfe80-662a-11ea-8eaa-7f7cd4b0d464.png)
![end2](https://user-images.githubusercontent.com/62147746/76688158-b46e2b80-662a-11ea-84dc-a0b3bf0014b9.png)


thanks in advance for your help

**Comment by myspaghetti** [comment] 2020-03-14 20:13
Delete the state that's using the VISO file in another virtual machine...

**Comment by PatrickG** [comment] 2020-03-15 09:50
What does this has to do with the resource busy error?

**Comment by myspaghetti** [comment] 2020-03-15 11:01
@PatrickG at first it seemed like JGithub56 had a file access issue so I directed him to this thread to troubleshoot. Now it appears he had a VirtualBox configuration issue that is unrelated to this thread. Sorry for the confusion.

**Comment by JGithub56** [comment] 2020-03-15 14:33
I just had to delete the lines where `.viso` and in particular `{fc37...92f7}` appeared in the file` macOS.vbox`, I relaunched the script and everything worked
Thanks for your help, you did a great job !

**Comment by myspaghetti** [comment] 2020-03-22 07:55
Closing until further information is available.

**Comment by Scraft** [comment] 2020-04-10 09:53
I am hitting this same issue, I have a 6700K processor and ASUSTeK STRIX B250F GAMING motherboard, and had to add:
`--cpu-profile "Intel Core i7-6700K" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff`
to get past the initial loop, with that it gets to the issue listed here. What I ntoiced is if I continually issue the command, it gets a different % through restoring each time, so I left it on a loop attempting to do it all night. When I came to this machien this morning, the terminal window has disappeared, so I rebooted the machine, however it just goes into a UEFI interactive shell.

From reading through the above comments, it isn't clear to me if there is something I can do to resolve this or not?

**Comment by myspaghetti** [comment] 2020-04-10 12:13
@Scraft thank you for the extensive info and troubleshooting. I am still not able to reproduce this issue, there's no workaround, and I don't know what causes the issue.

If you wouldn't mind, please attach the output of `./macos-guest-virtualbox.sh troubleshoot > troubleshoot.txt`

**Comment by Scraft** [comment] 2020-04-10 12:50
I tried a few different VM images of Catalina, tried on two different HDs, rebooted machine a few times, but didn't find a solution.

So I went back to the start, deleted all previous attempts of making the VM, and ran this script again, with just the cpu-profile setting, and it got all the way through the first time and without any hitches.

This is a little frustrating as I predict someone else will find this thread in the future, read to the end, see I got it working, but not see any instructions on how to fix it. So the best I can offer is:

- Install Ubuntu for Windows 10
- Remove all machines from Virtual Box
- Delete any files associated with above machines
- Ensure Windows HyperVisor is disabled
- Restart your machine twice (probably insane, but my first reboot after disabling HyperVisor also did a Windows Update, and it wasn't working, so maybe a second was needed?)
- If you have a 6700K CPU then ensure the following is added to the script:
`--cpu-profile "Intel Core i7-6700K" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff`
- Run the script from Ubuntu shell, hit enter when it asks you until it completes

@myspaghetti if there is still anything I can do to help diagnose this, I am happy to. I do not have the faulty machine anymore (as I deleted it as part of my steps above), but I am happy to retry, changing options, etc. FWIW, what I used to keep it running overnight again and again until it succeeded was:

1. Create a script in tmp called run.sh and pasted the contents of the command in the shell into there
2. chmod +x /tmp/run.sh
3. Run the following in the shell:
`while /tmp/run.sh
do
echo "Trying again"
done`

![image](https://user-images.githubusercontent.com/294599/78991998-3706df80-7b32-11ea-8694-d640cad353a4.png)

**Comment by filipesarturi** [comment] 2020-04-17 00:12
same here

**Comment by myspaghetti** [comment] 2020-04-17 07:17
@filipesarturi please attach the output of `./macos-guest-virtualbox.sh troubleshoot > troubleshoot.txt`

**Comment by filipesarturi** [comment] 2020-04-17 22:06
> @filipesarturi please attach the output of `./macos-guest-virtualbox.sh troubleshoot > troubleshoot.txt`

disabling hyper-v and reinstalling worked perfectly!

**Comment by slashinpdx** [comment] 2020-04-25 19:22
Have also received the attached error 256 at multiple percentages.  Retrying multiple times has gotten me past it to the point of the attached error image regarding checksum failure.  It's noteworthy that my virtual machine will never get to the language screen unless set the number of processors to 1.  This was the same with my failed attempt to install every other version of OS X.  Any more than 1 also causes extreme sluggishness until finally rebooting into a loop.  

- Have hyper-v disabled.  
- Working on an i7 3770 @ 3.40GHz, Windows 10 Pro, latest release, WSL 1, Ubuntu  2004.2020.424.0

- Have tried "--cpu-profile "Intel Core i7-6700K" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff" with and without the cpu-profile flag.  
- Have tried with fixed and standard virtual disks.  

One attempt (after getting the failed checksum error and shutting down manually) got me to a point where it boots on the macOS virtual drive, but thereafter loops when it hits the GUI.

Any suggestions?

![Checksum failed2](https://user-images.githubusercontent.com/8278361/80288824-7a934900-86ef-11ea-84b9-28e3ebfc965e.png)
![Intel i7 3770](https://user-images.githubusercontent.com/8278361/80288825-7b2bdf80-86ef-11ea-9283-820795341304.png)
![Checksum failed](https://user-images.githubusercontent.com/8278361/80288826-7b2bdf80-86ef-11ea-9040-13726ff9629f.png)

**Comment by myspaghetti** [comment] 2020-04-26 06:08
@slashinpdx hi, thanks for the detailed bug report!

If you don't mind please provide the file `troubleshoot.txt` generated by `./macos-guest-virtualbox.sh troubleshoot > troubleshoot.txt`

At this point I'm trying to collect information from everybody reporting the error because I haven't been able to reproduce it.

**Comment by GoldenTao** [comment] 2020-04-27 05:24
@myspaghetti I'm seeing the same issue, but the troubleshooter doesn't seem to finish and save the file.  It seems to be getting hooked up on check_dependencies in the script.  Haven't debugged into that yet to find exactly what's causing that yet.

I'm running a 6700K (Hyper V enabled for Docker)

When running the script normally, I hit a couple of issues, without setting a chipset profile I got a boot loop, by setting the profile as the Xeon I could get OSX to load but hit the 256 error.

By using --cpu-profile "Intel Core i7-6700K" --cpuidset 00000001 000106e5 00100800 0098e3fd was able to also get OSX installer to boot, but same 256 error.

Have also tried fixed drive sizes, that also didn't change anything.

I'll try to get some time tonight to dig into the troubleshooter further, but let me know if there is something else I can try there.

**Comment by myspaghetti** [comment] 2020-04-27 06:54
@GoldenTao if you're able to run `check_dependencies` outside of `troubleshoot` then there's no reason for `troubleshoot` to fail. If you're running Hyper-V then macOS won't work anyway, unless Oracle retooled their NEM engine recently which doesn't seem likely from the changelog, but they have been known to silently add, remove, and fix features in the past.

There is definitely a pattern of people using the `cpuidset` configuration here, which can cause these sort of low-level IO problems in the VM.

**Comment by riverar** [comment] 2020-04-27 07:02
@myspaghetti VirtualBox 6.0+ taps into WHPX (introduced back in Windows 10 April 2018 Update) for its paravirtualization, so Hyper-V enabled state should work at the expense of some performance, right? Or is there a particular NEM feature you're concerned about?

**Comment by riverar** [comment] 2020-04-27 07:06
Wild guess here, but judging by the differing checksum in multiple runs, could this checksum code be relying on processor features that are claimed to be present via forced cpuidset (but aren't actually present on the host)? It's not clear how VirtualBox handles this scenario (panic? emulation?).

**Comment by myspaghetti** [comment] 2020-04-27 07:27
@riverar I don't really know what features NEM provides, only that it's been consistently reported that macOS doesn't work on NEM before. If the latest VirtualBox version runs macOS with NEM then I'll remove the WSL2/Hyper-V warning from the script.

I think your wild guess is correct. Hopefully future reports will shed more light on this.

**Comment by myspaghetti** [comment] 2020-05-05 16:12
Marking this as duplicate of #200 
Please use that issue for any future reports, please attach the output of `./macos-guest-virtualbox.sh troubleshoot > troubleshoot.txt` in any future reports.

**Closed by myspaghetti** 2020-05-05 16:12 UTC
Labels: bug, duplicate, non-script
