### ISSUE TITLE
VM hangs on install

### ISSUE THREAD

**Issue by aidenmitchell** [myspaghetti/macos-guest-virtualbox#182] opened 2020-04-01 19:32 UTC
![image](https://user-images.githubusercontent.com/30846409/78178603-c0246500-7414-11ea-8f23-72161fe9a069.png)
![image](https://user-images.githubusercontent.com/30846409/78178634-cadefa00-7414-11ea-945e-2fb56e4d0120.png)

**Comment by myspaghetti** [comment] 2020-04-02 00:10
Hi, thanks for the bug report.

Could you run the following and attach the resulting log file? `./macos-guest-virtualbox.sh troubleshoot > log.txt`

**Comment by aidenmitchell** [comment] 2020-04-02 01:12
[log.txt](https://github.com/myspaghetti/macos-guest-virtualbox/files/4418336/log.txt)

**Comment by myspaghetti** [comment] 2020-04-02 01:42
Thanks. I've tweaked the output of `troubleshoot` a little bit, could you download [version 0.88.7](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/7968d114938ca54ba1a42ded2b13108eef73476e/macos-guest-virtualbox.sh) of the script and upload the new output of `troubleshoot`?

In the meantime you could try powering off the VM, entering one of the following commands, powering on the VM to see if it boots, and if it doesn't then power it off and try another one:

```
VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-2635QM"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-3960X"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i5-3570"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-5600U"
VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i7-6700K"
```

**Comment by aidenmitchell** [comment] 2020-04-02 01:55
```VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"``` worked! 
Is there a way to resume your script?

**Comment by myspaghetti** [comment] 2020-04-02 02:01
Yes, run `./macos-guest-virtualbox.sh populate_virtual_disks populate_macos_target` or just run the script from the beginning, it will prompt to delete the existing VM but keep the downloaded files.

**Comment by myspaghetti** [comment] 2020-04-02 02:03
Closing as duplicate of #8

**Closed by myspaghetti** 2020-04-02 02:03 UTC
Labels: bug, duplicate, non-script

**Comment by aidenmitchell** [comment] 2020-04-02 02:06
Great, thanks for your help.
