### ISSUE TITLE
"Couldn't find the requested download URL in the Apple catalog. Exiting."

### ISSUE THREAD

**Issue by l-g** [myspaghetti/macos-guest-virtualbox#142] opened 2020-01-08 22:37 UTC
When trying to install Mojave or High Sierra I get an error message

"Couldn't find the requested download URL in the Apple catalog. Exiting."

Seems quite clear what it is about...

**Comment by myspaghetti** [comment] 2020-01-09 08:38
Most likely a duplicate of [issue 141](https://github.com/myspaghetti/macos-guest-virtualbox/issues/141) which is solved by using `gcsplit` `gtac` and `gsplit`

**Closed** 2020-01-09 17:24 UTC
Labels: bug, duplicate
