### ISSUE TITLE
Converting from raw image file="Mojave_BaseSystem.img" to file="Mojave_BaseSystem.vdi" on WSL

### ISSUE THREAD

**Issue by zahroc** [myspaghetti/macos-guest-virtualbox#152] opened 2020-01-29 18:21 UTC
Running the script on WSL and the C:\Program Files\Oracle\VirtualBox is in the system path. Mojave_BaseSystem.img is in the current $PWD
Error is:

Archive successfully decompressed as Mojave_BaseSystem.img
Converting from raw image file="Mojave_BaseSystem.img" to file="Mojave_BaseSystem.vdi"...
VBoxManage.exe: error: Cannot open file "Mojave_BaseSystem.img": VERR_FILE_NOT_FOUND

**Comment by myspaghetti** [comment] 2020-01-29 23:24
Possible duplicate of [issue 83](https://github.com/myspaghetti/macos-guest-virtualbox/issues/83).

On WSL on Windows 10 earlier than version 1903 the script needs to run on a non-WSL path. The script outputs this warning:

>The script requires Windows 10 version 1903 or higher to run properly on WSL.
>For lower versions, please run the script on a path on the Windows filesystem,
>for example  "/mnt/c/Users/Public/Documents"

If you're running the script on Windows 10 1903 or later please post your Windows version and WSL version. Another possible issue is file permissions; make sure you run the script *without* elevated privileges and that VirtualBox can access the script's working directory.

**Comment by zahroc** [comment] 2020-01-30 13:32
Running on Windows 10 1909 Build 18363.592 and WSL 1
That corrected the issue, running it from the Windows files system made it to the end.

**Comment by myspaghetti** [comment] 2020-01-30 16:35
>1909

Supposed to be fixed in that version, must be a regression. Maybe the warning should apply to all WSL1 versions.

**Closed by myspaghetti** 2020-01-30 16:35 UTC
Labels: bug

**Comment by myspaghetti** [comment] 2020-01-30 16:52
Added the warning for all WSL (1) versions in [script version 0.85.2](https://github.com/myspaghetti/macos-guest-virtualbox/commit/35a71eda27560da06ebe2d0e9b4f678b6b29ed0d)
