### ISSUE TITLE
"fs1 is not a correct mapping"

### ISSUE THREAD

**Issue by Black00Z** [myspaghetti/macos-guest-virtualbox#101] opened 2019-09-17 19:52 UTC
Hello there and sorry for causing trouble again, using the newest version of the script got me stuck at the "mapping table". ` fs1 is not a correct mapping` . Seems like the issue similar to #32 but there wasn't really a solution so I opened a new issue. I'm on Linux Mint, trying to boot Mojave. :)

![Mapping_table](https://user-images.githubusercontent.com/12191067/65074025-4bb43800-d994-11e9-80eb-a5263a117a64.png)

I am not 100% sure but this time as well it didn't  prompted a license agreement. It still booted up though.

**Comment by myspaghetti** [comment] 2019-09-18 09:15
No trouble, I want the script to work, and you're helping.

The latest version of the script ([0.75.3](https://github.com/myspaghetti/macos-guest-virtualbox/blob/d2dc2403f05cc4dda0a7d8fce860718ac551710f/macos-guest-virtualbox.sh)) skips the license prompt.

* Did the installer report that it reached 100% in Terminal?
* What were the last few messages given by the script on the host?
* Please attach `$HOME/.VirtualBox/Machines/<vm name>/Logs/VBox.log`

**Comment by Black00Z** [comment] 2019-09-18 21:49
I'm glad I can help in any kind of way.
I'm on version 0.75.3 of the script.

- It reached till the end and said "macOS installation should complete in a few minutes." and more but it never booted. Hence the last message / the last part of the script being the `boot_macos_and_clean_up` part where it didn't continued.

- [Here](https://github.com/myspaghetti/macos-guest-virtualbox/files/3628485/VBox.log) is the last VBox.log. It actually had 4 in the folder but this should be the last one.

**Comment by myspaghetti** [comment] 2019-09-19 11:38
Looks like the installer failed to start. You should have seen this in the guest:
![VirtualBox_macOS_19_09_2019_14_31_15](https://user-images.githubusercontent.com/31696646/65240654-71ebec00-daea-11e9-8550-6daee9031b42.png)
Then the EFI APFS drivers are copied to the target VDI (which they were), and then the installer starts (which it didn't).

If you didn't see `Preparing: 100%` and `Restarting...` then the installer failed to copy the installation files to the target, or even partition the target by the looks of it.

**Comment by Black00Z** [comment] 2019-09-23 07:51
I'm sorry but it never showed this window. I am trying to download everything the 3rd time and I will report back asap.

**Comment by Black00Z** [comment] 2019-09-25 09:57
Got High Sierra running. It opened the "Preparing.." windows and booted by itself!

But Mojave is still not woking. I think I will try it another time the next days. Thanks again for the help :)

**Comment by myspaghetti** [comment] 2019-09-25 11:01
Because the checksums on the host were correct but the checksums on the guest were incorrect, it's very likely that the files got corrupted when transferred from the VISO to the VDI. I was able to make the installer fail but I'm unable to get the files on the VDI to be corrupt. You can start another issue or reopen this issue if you can provide a method to reproduce the issue. I'm closing this issue until new information is available.

**Closed by myspaghetti** 2019-09-25 11:01 UTC
Labels: bug

**Comment by myspaghetti** [comment] 2019-09-25 11:04
You might also want to post on [issue 84 - "starttoinstall" fails](https://github.com/myspaghetti/macos-guest-virtualbox/issues/84)
