### ISSUE TITLE
Error writing script on mac shell

### ISSUE THREAD

**Issue by JGithub56** [myspaghetti/macos-guest-virtualbox#173] opened 2020-03-13 15:35 UTC
I have an error when the script write automatically this
`
disks="$(diskutil list | grep -o "\*[0-9][^ ]* GB *disk[0-9]$" | grep -o "[0-9].*" | sort -gr | grep -o disk[0-9] )" && '\
'disks=(${disks[@]}) && '\
'if [ -z "${disks}" ]; then echo "Could not find disks"; fi && '\
'[ -n "${disks[0]}" ] && '\
'diskutil partitionDisk "/dev/${disks[0]}" 1 GPT APFS "'"${vm_name}"'" R && '\
'diskutil partitionDisk "/dev/${disks[1]}" 1 GPT JHFS+ "Install" R && 
`
and then this
`asr restore --source "/Volumes/'"${macOS_release_name:0:5}-files"'/BaseSystem.dmg" --target /Volumes/Install --erase --noprompt && '\
'app_path="$(ls -d "/Volumes/"*"Base System 1/Install"*.app)" && '\
'install_path="${app_path}/Contents/SharedSupport/" && '\
'mkdir -p "${install_path}" && cd "/Volumes/'"${macOS_release_name:0:5}-files/"'" && '\
'cp *.chunklist *.plist *.dmg "${install_path}" && '\
'echo "" && echo "Copying the several-GB InstallESD.dmg to the installer app directory" && echo "Please wait" && '\
'if [ -s "${install_path}/InstallESD.dmg" ]; then '\
'rm -f "${install_path}/InstallESD.dmg" ; fi && '\
'for part in InstallESD.part*; do echo "Concatenating ${part}"; cat "${part}" >> "${install_path}/InstallESD.dmg"; done && '\
'sed -i.bak -e "s/InstallESDDmg\.pkg/InstallESD.dmg/" -e "s/pkg\.InstallESDDmg/dmg.InstallESD/" "${install_path}InstallInfo.plist" && '\
'sed -i.bak2 -e "/InstallESD\.dmg/{n;N;N;N;d;}" "${install_path}InstallInfo.plist" && 
` 

The problem is, when the script automatically writes on the mac virtual machine prompt, the keyboard that writes is qwerty and it's a pc keyboard, whereas if I try to write myself, I notice that it's an azerty and mac keyboard, so for example the "-" is not found at the level of the key "6" but at the level of the key "+ / =" near to the backspace key.

I tried to write everything by hand, the first line (`disks="$(diskutil list | grep -o "\*[0-9][^ ]* GB *disk[0-9]$" | grep -o "[0-9].*" | sort -gr | grep -o disk[0-9] )" `) of code seems to work (no error) but from the second line (`disks=(${disks[@]})`) I have the error: "command not found"

I tried setxkbmap or loadkeys but nothing is installed and i don"t know how to install them.

so I don't shutdown the VM, waiting for your help.

I'm on linux, ubuntu 18.04.4 LTS, virtualbox 6.1.4

Thanks in advance

**Comment by myspaghetti** [comment] 2020-03-13 20:04
Thanks for the bug report.

Is the problem with the script that [the keyboard input breaks up (issue 114)](https://github.com/myspaghetti/macos-guest-virtualbox/issues/114)? If so there's a workaround available.

If it's something else, please describe what specifically is wrong with the keyboard input. Are characters missing? Is there an error message?

**Comment by JGithub56** [comment] 2020-03-14 09:09
I've solved a few problems, coming from typos (I cannot paste your script, I've to type everything again with a blind keyboard).
I've reached the command: 
![umount](https://user-images.githubusercontent.com/62147746/76678833-7f86b800-65db-11ea-8704-e3411057299b.png)

where disk0 is the second largest disk available.

the error says that I couldn't unmount the disk and if I try to do it by hand, 
`umount: disk0: not currently mounted`

waiting for your answer,

thanks

**Comment by myspaghetti** [comment] 2020-03-14 09:19
Could you please describe what is specifically wrong with the automatic character input of the script? Are there characters missing? Is there an error message?

**Comment by JGithub56** [comment] 2020-03-14 09:44
I have solved the first problem by typing by hand the script (I missed some characters that'"s why it do not works)

but I have now  this problem just written above.

**Comment by JGithub56** [comment] 2020-03-14 09:58
IGNORE the previous messages. 
I've noticed that we need to choose the english language to have to your script functionning

But now there is this issue:

![issue](https://user-images.githubusercontent.com/62147746/76679693-abf20280-65e2-11ea-8276-3341be108bb2.png)

Any ideas?

**Comment by myspaghetti** [comment] 2020-03-14 12:24
>I've noticed that we need to choose the english language to have to your script functionning

The script requires that you don't interact with the virtual machine; the default language is English, if you manually interact with the virtual machine then it enters an unknown state and the script might not be able to continue.

>`Couldn't unmount disk`

Similar to [issue 128](https://github.com/myspaghetti/macos-guest-virtualbox/issues/128), I can't reproduce this issue. I'm marking this as duplicate and merging this issue with issue 128.

**Closed by myspaghetti** 2020-03-14 12:24 UTC
Labels: bug, duplicate
