### ISSUE TITLE
Catalina worked, but not Mojave

### ISSUE THREAD

**Issue by sgehrman** [myspaghetti/macos-guest-virtualbox#177] opened 2020-03-19 12:47 UTC
Can't attach Nvram Storage driver (VERR_PDM_CFG_MISSING_DRIVER_NAME).

Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

Any ideas?

**Comment by sgehrman** [comment] 2020-03-19 13:04
I'm on Linux, AMD, VB 6.1.4

**Comment by myspaghetti** [comment] 2020-03-19 15:36
>`Can't attach Nvram Storage driver (VERR_PDM_CFG_MISSING_DRIVER_NAME).`

Are you by any chance using an old version of the script? Please use [the latest version (0.88.3)](https://raw.githubusercontent.com/myspaghetti/macos-guest-virtualbox/master/macos-guest-virtualbox.sh). The script hasn't used the NVRAM driver since version 0.80.0.

**Comment by myspaghetti** [comment] 2020-03-19 15:37
Duplicate of #135

**Closed by myspaghetti** 2020-03-19 15:37 UTC
Labels: duplicate

**Comment by sgehrman** [comment] 2020-03-19 20:33
I'm using the latest 88.3.  I didn't even know about this script until yesterday. I just compared what I have to your latest and they are identical.

**Comment by myspaghetti** [comment] 2020-03-20 03:22
Did you make any manual modifications to the virtual machine? Please post the `.vbox` file.
