### ISSUE TITLE
License prompt won't appear

### ISSUE THREAD

**Issue by Black00Z** [myspaghetti/macos-guest-virtualbox#99] opened 2019-09-05 10:36 UTC
Quick thanks for this wonderful script :)

I'm having an issue which someone else had in this issue #79 . I couldn't find a way to get past it unlike the other op did with a simple reboot.

I'm at the "start_the_installer_app" step and no matter what I do the step that includes this part of the script: `app_path="$(ls -d /Install*.app)" && cd "/${app_path}/Contents/Resources/"; ./startosinstall --volume "/Volumes/MacOS/"` won't get me to the license prompt.
 
Am I missing something maybe?

**Comment by myspaghetti** [comment] 2019-09-05 10:48
Could you boot into the virtual machine, run Terminal, and post the output of the following:
```
ls /Install*.app/Contents/SharedSupport/
```

**Comment by Black00Z** [comment] 2019-09-09 10:41
I'll add some more information as soon as I'm booting it again.

**Comment by Black00Z** [comment] 2019-09-11 08:01
This is the output:

AppleDiagnostics.chunklist     InstallESD.dmg
AppleDiagnostics.dmg            InstallInfo.plist
BaseSystem.chunklist            InstallInfo.plist.bak
BaseSystem.dmg                   InstallInfo.plist.bak2


Additional information to the rest: I'm on Linux Mint 19.2 with Vbox 6.0

**Comment by myspaghetti** [comment] 2019-09-11 10:18
Thanks. Good news: I can reproduce the error. Bad news: I don't know what's causing it. Possibly a mount options issue. Will investigate.

**Comment by myspaghetti** [comment] 2019-09-11 10:28
It appears `InstallESD.dmg` fails to mount sometimes. Investigating.

**Comment by myspaghetti** [comment] 2019-09-11 10:51
@Black00Z thank you! Could you upload `/var/log/install.og` from the virtual machine?

- boot into the virtual machine
- start "Get Help Online" (Safari)
- enter "macos guest virtualbox" in the address bar and click on the first result
- sign into github
- browse to this page
- click "Attach files [...]" directly at the bottom of the comment text field)
- type `/var/log` and press enter (the directory is hidden so you'll have to type it manually in the path prompt that appears when you press `/`)
- choose install.log

Additionally it would be helpful if you could post the `md5sum` (or `sha1sum` or `sha256sum`) of `*InstallESDDmg.pkg` from the script's working directory on the host. For example the most recent Mojave InstallESDDmg.pkg matches these checksums:
```
sha256sum Mojave_InstallESDDmg.pkg
ffa3fcc7e08b6134dca9f481f15aabce3fd80159951551dccdcd29df1a59e777 *Mojave_InstallESDDmg.pkg
```

**Comment by Black00Z** [comment] 2019-09-13 09:20
Oops didn't knew curl would work on Mac too. Tried MacOS for the first time and the messed up keylayout is a pain hahaha.

Regardless here is the install.log: `http://ix.io/1UYw`

**Comment by myspaghetti** [comment] 2019-09-13 17:02
Thanks. The log says:
```
2019-09-13 08:32:57+00 MacBook-Pro osinstallersetupd[597]: mountDiskImageWithPath: /Install macOS Mojave.app/Contents/SharedSupport/InstallESD.dmg
2019-09-13 08:33:00+00 MacBook-Pro osinstallersetupd[597]: Couldn't mount dmg! (error code 112)
2019-09-13 08:33:00+00 MacBook-Pro osinstallersetupd[597]: Failed to mount the payload dmg (/Install macOS Mojave.app/Contents/SharedSupport/InstallESD.dmg)
2019-09-13 08:33:00+00 MacBook-Pro osinstallersetupd[597]: Fatal error setting up daemon, install document damaged?
```
Perhaps `Mojave_InstallESDDmg.pkg` got damaged when split onto the VISO or concatenated onto the installer VDI.

Please run in the virtual machine's terminal `md5 /Install*/Contents/SharedSupport/InstallESD.dmg`

The md5sum should be `ea6bceb1a8ac0e9de500e61492cf8ed5`

**Comment by Black00Z** [comment] 2019-09-16 10:07
The md5sum of the file  `/Install*/Contents/SharedSupport/InstallESD.dmg` is `c0c19609cd167b40839e23f4c12425e8`

**Comment by myspaghetti** [comment] 2019-09-17 11:45
Thanks. `InstallESD.dmg` is apparently damaged. You can fix it by deleting the `*.part*` files from the script's working directory and restart the script. If the issue persists I'll attempt to reproduce it.

If you still want to troubleshoot, here are the md5sums of the part files:
```
ee3bda969419e0f14490b9bdb15fe8dd *Mojave_InstallESD.part00
001c83ed37867d64d7cbf850695ea6e9 *Mojave_InstallESD.part01
0d616f7d5454278ad161a24fa44ac9e4 *Mojave_InstallESD.part02
24fa79e8ff8507a9b00c258c0d9b81a1 *Mojave_InstallESD.part03
056ad9470447c5678a2ec40dc77372be *Mojave_InstallESD.part04
3153d1167ee97e24e2ed4dbb63ea392b *Mojave_InstallESD.part05
```
If yours match, it means the error probably happened when they were concatenated onto the VDI.

**Comment by Black00Z** [comment] 2019-09-17 18:37
The Md5sum of my Files:

`- ee3bda969419e0f14490b9bdb15fe8dd *Mojave_InstallESD.part00`

`- 001c83ed37867d64d7cbf850695ea6e9 *Mojave_InstallESD.part01`

`- 0d616f7d5454278ad161a24fa44ac9e4 *Mojave_InstallESD.part02`

`- 24fa79e8ff8507a9b00c258c0d9b81a1 *Mojave_InstallESD.part03`

`- 056ad9470447c5678a2ec40dc77372be *Mojave_InstallESD.part04`

`- 3153d1167ee97e24e2ed4dbb63ea392b *Mojave_InstallESD.part05`

Thanks again and I'll try it right now. Gonna update the script now and will report back asap.

**Comment by myspaghetti** [comment] 2019-09-18 09:18
Closing as I can't reproduce the bug. All the `*.part*` files are fine so the issue must be at the part of the script where they were concatenated into `InstallESD.dmg`, which might be a duplicate of [issue 63, errant keystrokes](https://github.com/myspaghetti/macos-guest-virtualbox/issues/63).

**Closed by myspaghetti** 2019-09-18 09:18 UTC
Labels: bug, won't fix
