### ISSUE TITLE
keyscan code: invalid associative array key

### ISSUE THREAD

**Issue by StefanTheWiz** [myspaghetti/macos-guest-virtualbox#126] opened 2019-11-17 11:48 UTC
Hi,

I'm running the script on Bash 4 and I'm running into this error:
```bash
macos-guest-virtualbox.sh: line 580: []]=1B 9B: bad array subscript
macos-guest-virtualbox.sh: line 580: [@]=2A 03 83 AA: invalid associative array key
macos-guest-virtualbox.sh: line 580: [*]=2A 09 89 AA: invalid associative array key
```

Version information:
```
$ uname -a
Linux vm-host-01 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
```

I've got a fix which I could put in a pull request. However, is anyone else having this issue?
It's preventing the script from typing the characters [, @, * on the OS X terminal.

**Comment by myspaghetti** [comment] 2019-11-17 18:49
This is not a bug in the script; bash should accept associative array keys when they're quoted, for example `"@"` and `"*"`. Are you running the script in any special way that strips the quotes?

**Comment by myspaghetti** [comment] 2019-11-17 19:17
[Possibly a bug with some versions of bash and associative arrays with certain characters.](https://lists.gnu.org/archive/html/bug-bash/2011-05/msg00005.html)

**Comment by freeload101** [comment] 2019-11-18 14:47
worked fine with me on cygwin 
GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)

**Comment by myspaghetti** [comment] 2019-11-18 17:00
Tested on a live image of CentOS `7.7.1908`:
```
Linux localhost 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
```

Could not reproduce. @StefanTheWiz please run a default-configuration instance of bash to make sure this is not a bash configuration issue, for example a variable expansion configuration issue.

**Comment by StefanTheWiz** [comment] 2019-11-19 23:04
I run my scrips with `set -euxo pipefail;` at the top. 
However, here's a simpler test I've just ran and still failing. I've just installed CentOS minimal on the machine in question a few days ago - say within the last week so it can't be that different from the live image.

test.sh:
```bash
#!/bin/bash

declare -A ksc=(
  ["]"]="1B 9B"
  ["@"]="2A 03 83 AA"
  ["*"]="2A 09 89 AA"
)
```

Then 
```
chmod +x test.sh
./test.sh
```
Output:
```
./test.sh: line 3: []]=1B 9B: bad array subscript
./test.sh: line 3: [@]=2A 03 83 AA: invalid associative array key
./test.sh: line 3: [*]=2A 09 89 AA: invalid associative array key
```

It's probably an issue with bash but what I'm suggesting in the PR is a more robust approach.

**Comment by myspaghetti** [comment] 2019-11-20 04:13
Thank you very much for debugging! I reproduced the issue with a clean install of CentOS `7.7.1908 minimal`. Likely the distro's version of bash has incorrect associative array key parsing.

The pull request is definitely a workaround but I wouldn't call it more robust, it relies on backslash escaping and it makes single-quote and double-quote a string sanitization issue that cascade down the script.

Closing as "wont fix" but thanks again for the detailed bug report and debugging.

**Closed by myspaghetti** 2019-11-20 04:13 UTC
Labels: non-script

**Comment by myspaghetti** [comment] 2019-11-20 04:14
Thank you very much for debugging! I reproduced the issue with a default install of CentOS `7.7.1908 minimal`. Likely the distro's version of bash has incorrect associative array key parsing.

The pull request is definitely a workaround but I wouldn't call it more robust, it relies on backslash escaping and it makes single-quote and double-quote a string sanitization issue that cascade down the script.

Closing as "wont fix" but thanks again for the detailed bug report and debugging.

**Comment by myspaghetti** [comment] 2019-11-20 04:40
I've filed [a bug report on bugs.centos.org](https://bugs.centos.org/view.php?id=16754)

**Comment by xaminmo** [comment] 2020-01-17 01:04
Related:  Per issue https://github.com/myspaghetti/macos-guest-virtualbox/issues/147, commit https://github.com/myspaghetti/macos-guest-virtualbox/commit/68c9fb7f76b89d699b89fac679ed924a64c212b3  updated the BASH requirement to 4.3 due to buggy associative array implementation in 4.2 and lower.
