### ISSUE TITLE
"starttoinstall" fails

### ISSUE THREAD

**Issue by situssoft** [myspaghetti/macos-guest-virtualbox#84] opened 2019-07-16 12:38 UTC
Fails when unpacking the installer @ 74.4% regardless of how many times I download and which version of macOS I attempt to install.

Preparing 74.4%         An error occurred validating the installer data. The download is either damaged or incomplete.

I've attempted this a few times now, I don't generally have any issues with my network or downloading fro the web.

Any help appreciated.

**Comment by situssoft** [comment] 2019-07-16 14:23
Well, I tried a few more times, without deleting any of the downloaded files and eventually I've managed to get through to the install. 

Sorry, no idea why this has been unreliable.

**Comment by myspaghetti** [comment] 2019-07-16 16:32
Could not reproduce. Closing until further details are provided.

**Comment by FarmaanElahi** [comment] 2019-09-17 07:53
Even I am facing the same issue.Mine stuck as 73.6% with the same message as above

**Comment by myspaghetti** [comment] 2019-09-17 11:55
Hi. Can you provide the md5sum for the `*.part*` files on the host and the `InstallESD.dmg` file on the guest? On the host, execute in a terminal on the script's working directory:
```
for part in *.part*; do md5sum "${part}"; done
```
On the guest, open Terminal and execute:
```
md5 /Install*/Contents/SharedSupport/InstallESD.dmg
```
It would also be helpful if you upload the installer log after the installation fails, for example by executing the following in Terminal:
```
curl -F 'f:1=@/var/log/install.log' ix.io
```

**Comment by myspaghetti** [comment] 2019-09-18 09:35
Hi. Can you provide the md5sum for the `*.part*` files on the script's working directory on the host, the md5sum for the `InstallESD.dmg` file on the guest, upload the `install.log` file from the guest and `VBox.log` from the host?

----

The virtual machine log `VBox.log` is found in the [VirtualBox VM log directory](https://blogs.oracle.com/scoter/virtualbox-log-files-v2).

----

Installer log can be uploaded from the guest machine with the following Terminal command after the installer fails:
```
curl -F 'f:1=@/var/log/install.log' ix.io
```

----

Checksum of `InstallESD.dmg` can be computed on the guest machine with the following Terminal command:
```
md5 /Install*/Contents/SharedSupport/InstallESD.dmg
```

----

Checksums for the files split from `InstallESD.dmg` on the host machine can be computed by executing the following command at the script's working directory:
```
for part in *.part*; do md5sum "${part}"; done
```

**Comment by myspaghetti** [comment] 2019-10-19 16:19
Closing until further information is provided.

**Closed by myspaghetti** 2019-10-19 16:19 UTC
Labels: bug

**Comment by kklopfenstein** [comment] 2020-07-03 11:02
My installer is consistently failing at 77.8%.

`VBox.log`
http://ix.io/2qLi

`VBox.log.1`
http://ix.io/2qLj

`VBox.log.2`
http://ix.io/2qLl

Installer log

http://ix.io/2qLf
http://ix.io/2qLg
http://ix.io/2qLh

Checksum of `InstallESD.dmg`

```
15975e4c8b90c6a84893ded21328e5e0
```

Checksums for the files split from `InstallESD.dmg` 

```
4f6b85bf96520a2f53609c4bad750bd1  Catalina_InstallESD.part00
10bf7f695295e7d450d67591f6c5a750  Catalina_InstallESD.part01
c14dccf8d7d3d6fcc62ff7c6b40ad852  Catalina_InstallESD.part02
08cd6f166f6ede18b7ceb36ee6023e8c  Catalina_InstallESD.part03
746d9d2073103a5195831e4dd0882a7b  Catalina_InstallESD.part04
2a8f8367e44d5475c60436a2173bea57  Catalina_InstallESD.part05
46b87455d37aabb9bd51c41025eb92d9  Catalina_InstallESD.part06
be4dde6edb4cb41f34bdd028092b8b07  Catalina_InstallESD.part07
```

**Comment by myspaghetti** [comment] 2020-07-03 12:45
@kklopfenstein hi, thanks for the detailed bug report. The `md5` checksums for the Catalina `InstallESD.dmg` version `10.15.5.0.0.1591330708` do not match.

These are the correct `md5` checksums for the Catalina installer version `10.15.5.0.0.1591330708`:
```
ab79f4ee288e2140e1643a5e057e2510 *Catalina_BaseSystem.chunklist
d29307999bd0a2f0ec39037104f0f700 *Catalina_BaseSystem.dmg
4f6b85bf96520a2f53609c4bad750bd1 *Catalina_InstallESD.part00
10bf7f695295e7d450d67591f6c5a750 *Catalina_InstallESD.part01
c14dccf8d7d3d6fcc62ff7c6b40ad852 *Catalina_InstallESD.part02
08cd6f166f6ede18b7ceb36ee6023e8c *Catalina_InstallESD.part03
746d9d2073103a5195831e4dd0882a7b *Catalina_InstallESD.part04
2a8f8367e44d5475c60436a2173bea57 *Catalina_InstallESD.part05
46b87455d37aabb9bd51c41025eb92d9 *Catalina_InstallESD.part06
be4dde6edb4cb41f34bdd028092b8b07 *Catalina_InstallESD.part07
79d43951525fed978a5434b6d0672a9f *Catalina_InstallESDDmg.pkg
666cbff3d32f27dc13ef48ff45c017cd *Catalina_InstallInfo.plist
1a926bbb0e7cb1c068d08f990ad15cf8 *Catalina_AppleDiagnostics.chunklist
a65eb71e79dce3190b7e988261a74981 *Catalina_AppleDiagnostics.dmg
```

As you can see all the parts are correct but the complete `Catalina_InstallESDDmg.pkg` is damaged. There might have been an error concatenating the files.

Currently investigating the logs.

**Comment by myspaghetti** [comment] 2020-07-03 12:56
All the VBox logs look good on first glance. Investigating the `startosinstall` logs

**Comment by kklopfenstein** [comment] 2020-07-03 13:18
I've retried several times (with and without deleting temporary files). I get different checksums from `InstallESD.dmg` every time which seems in line with your concatenating theory.

**Comment by myspaghetti** [comment] 2020-07-03 14:43
@kklopfenstein sorry, can't troubleshoot it any further.

The VirtualBox configuration and script configuration are good, except the unsupported display resolution which is unlikely to be related.

You might have found a memory paging bug in VirtualBox.

**Comment by kklopfenstein** [comment] 2020-07-03 16:00
I reinstalled VirtualBox and retried the script with default settings (2 cpu, 4gb memory, 1280x800 etc). It worked the first time.
