### ISSUE TITLE
Black screen while "Press enter when the Language window is ready."

### ISSUE THREAD

**Issue by fkrahe** [myspaghetti/macos-guest-virtualbox#122] opened 2019-11-12 14:50 UTC
I'm using Ubuntu 19.10, with an AMD processor, and I'm trying to install Catalina. When the script reaches the point "Press enter when the Language window is ready.", my VirtualBox only shows a black screen. I'll try to press ENTER anyway. If it doesn not work, I'll try to install Mojave or Sierra. Any more info that I find I'll update here

**Comment by fkrahe** [comment] 2019-11-12 15:00
Ok, just pressing ENTER didn't work

> Press enter when the Terminal command prompt is ready.
> VBoxManage: error: Failed to send a scancode

I'll try the other OSes

**Comment by freeload101** [comment] 2019-11-12 15:04
If you don't see anything on the screen maybe:
* reinstall latest VBOX
* install latest Extension Pack

Make sure you can just boot off a normal ISO works 
Also be sure its not perm issue and just try it as root.

**Comment by fkrahe** [comment] 2019-11-12 15:05
I was running the script as a normal user, I'll try as root then. Thanks!

**Comment by fkrahe** [comment] 2019-11-12 15:09
This message is new (now that I'm root):

> Please make sure Oracle VM VirtualBox Extension Pack is installed, and that
> all installed VirtualBox extensions are listed as usable when
> running the command "VBoxManage list extpacks"

They are all usable

> Extension Packs: 2
> Pack no. 0:   VNC
> Version:      6.0.14
> Revision:     132055
> Edition:      
> Description:  VNC plugin module
> VRDE Module:  VBoxVNC
> Usable:       true 
> Why unusable: 
> 
> Pack no. 1:   Oracle VM VirtualBox Extension Pack
> Version:      6.0.14
> Revision:     133895
> Edition:      
> Description:  USB 2.0 and USB 3.0 Host Controller, Host Webcam, VirtualBox RDP, PXE ROM, Disk Encryption, NVMe.
> VRDE Module:  VBoxVRDP
> Usable:       true 
> Why unusable:

**Comment by fkrahe** [comment] 2019-11-12 23:48
With Mojave, no root, I got here https://imgur.com/a/MRdg67C

**Comment by myspaghetti** [comment] 2019-11-13 00:07
Hi. Please **don't** run the script with elevated privileges (root), this is not required and may be harmful. Your latest error appears to be a duplicate of [issue 8](https://github.com/myspaghetti/macos-guest-virtualbox/issues/8)

**Closed by myspaghetti** 2019-11-13 00:07 UTC
