### ISSUE TITLE
VBoxManage controlvm keyboardputscancode fails on macOS

### ISSUE THREAD

**Issue by houtanb** [myspaghetti/macos-guest-virtualbox#114] opened 2019-10-30 15:41 UTC
When I run the script with the following options
```
vmname="macOS"             # name of the VirtualBox virtual machine
storagesize=22000          # VM disk image size in MB. minimum 22000
cpucount=4                 # VM CPU cores, minimum 2
memorysize=8192            # VM RAM in MB, minimum 2048
gpuvram=128                # VM video RAM in MB, minimum 34, maximum 128
resolution="1280x800"      # VM display resolution
```
choosing C for Catalina, I eventually run into this problem:
```
Press enter when the Terminal command prompt is ready.

Partitioning target virtual disk.
VBoxManage: error: Failed to send a scancode
```
I have tried creating a Virtual Box for Mojave as well. It always fails on write to Terminal. Any suggestions?

**Comment by houtanb** [comment] 2019-10-30 16:58
I did it. It didn't work.
```
Partitioning target virtual disk.
VBoxManage: error: Failed to send a scancode
```
Here's a screenshot. Note I was not pressing any buttons on the keyboard when this happened (other than `Enter` when the Terminal window popped up
<img width="680" alt="Screen Shot 2019-10-30 at 17 55 58" src="https://user-images.githubusercontent.com/584723/67880335-bd100a80-fb3e-11e9-98c3-462a042f829c.png">

**Comment by houtanb** [comment] 2019-10-30 17:29
A second attempt:
```
Press enter when the Terminal command prompt is ready.

Partitioning target virtual disk.
VBoxManage: error: Failed to send a scancode
```
<img width="680" alt="Screen Shot 2019-10-30 at 18 28 44" src="https://user-images.githubusercontent.com/584723/67882812-2a259f00-fb43-11e9-8b92-510dbb037fbd.png">

**Comment by myspaghetti** [comment] 2019-10-30 17:56
Please download the attached file and rename it to `macos-guest-virtualbox.sh` and attempt to run it. You can skip all the stages before `populate_virtual_disks`. It's version `0.76.1` of the script with each keystroke sent by an individual instance of `VBoxManage` instead of sending entire lines with the same instance.

[macos-guest-virtualbox.txt](https://github.com/myspaghetti/macos-guest-virtualbox/files/3790458/macos-guest-virtualbox.txt)

I'll try to reproduce the issue later, meanwhile you can see if this change works around the issue.

**Comment by houtanb** [comment] 2019-10-31 10:54
It worked! Thanks so much :)

**Comment by myspaghetti** [comment] 2019-10-31 11:42
Could not reproduce on macOS 10.14.6 (18G103) i5-7360U with VirtualBox and Extension Pack version 6.0.14-133895-OSX.

- Is your processor very fast or very slow that it might affect the VM's input rate?
- Do you have any USB peripherals or other input devices that might affect keyboard input?
- Do you have any accessibility settings that might affect keyboard input?

**Comment by houtanb** [comment] 2019-10-31 13:03
Thanks for looking into this. I have a MacBook Pro Mid 2014, i7-4770HQ CPU @ 2.20GHz with 16 GB RAM running macOS 10.14.6

I have an external Dvorak keyboard connected via USB port. Other things connected by USB: mouse and iPhone.

No specific Keyboard/Accessibility settings

**Comment by myspaghetti** [comment] 2019-10-31 13:41
The external keyboard could be causing the issue. I tried running the script with an external keyboard on macOS and Windows on a couple of machines but I could not reproduce the bug.

If you could troubleshoot, it would be very helpful.

- On the guest, open TextEdit or Terminal or any other app that echoes keyboard input
- On the host, enter the following [replace "macOS" with the name of the VM if necessary] in Terminal:
```
faceroll=$(for i in $(seq 2 13) $(seq 16 27) $(seq 30 38) $(seq 43 53); do let j=i+128; printf '%02X %02X ' ${i} ${j}; done); faceroll="2A 04 84 AA ${faceroll} ${faceroll} ${faceroll} ${faceroll} ${faceroll} 1C 9C"; while True; do read -p "CTRL-C to quit, ENTER to continue"; VBoxManage controlvm macOS keyboardputscancode ${faceroll}; done
```

This will repeatedly prompt you to press enter to send keystrokes to the virtual machine. If the line aborts in the middle you should see a repeating character or no enter being pressed, as with the bug before.

Please test this a few times with the USB keyboard connected and disconnected, it would be very helpful in confirming or excluding the keyboard as the reason for the bug.

**Comment by houtanb** [comment] 2019-10-31 14:00
With keyboard plugged in

![Screen Shot 2019-10-31 at 14 58 46](https://user-images.githubusercontent.com/584723/67953218-fb650280-fbee-11e9-87b9-d14e07002318.png)

**Comment by houtanb** [comment] 2019-10-31 14:05
With all USB devices unplugged
<img width="1047" alt="Screen Shot 2019-10-31 at 15 04 11" src="https://user-images.githubusercontent.com/584723/67953654-d1f8a680-fbef-11e9-8a64-8f538722e61b.png">

**Comment by houtanb** [comment] 2019-10-31 14:06
NB: Using `GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)` installed via homebrew

**Comment by myspaghetti** [comment] 2019-10-31 15:53
So it's not the keyboard. I'll keep trying to reproduce the bug. Thanks for all your help!

**Comment by houtanb** [comment] 2019-10-31 15:57
No problem, thanks for all the work you put into this!

**Comment by thoernle** [comment] 2019-11-12 12:21
Had the same issue and it got fixed by your edited file. Please let me know if you need any further information.

**Comment by myspaghetti** [comment] 2019-11-12 13:30
@thoernle thank you very much.

- Any USB or Bluetooth devices that might produce/interrupt keyboard input?
- Dvorak keyboard layout?
- Any host settings that might affect keyboard accessibility?
- Is the host OS macOS?

**Comment by thoernle** [comment] 2019-11-12 14:47
- Any USB or Bluetooth devices that might produce/interrupt keyboard input?
Yes, I am using a Apple Magic Keyboard an a MacBook Pro

- Dvorak keyboard layout?
No, I am using "ABC - QWERTZ"

- Any host settings that might affect keyboard accessibility?
Nothing special set

- Is the host OS macOS?
macOS Mojave - Version 10.14.6

**Comment by myspaghetti** [comment] 2020-02-02 06:13
I'm sorry, I haven't been able to reproduce the issue still. Closing unresolved, feel free to reopen the issue or start a new one.

**Closed by myspaghetti** 2020-02-02 06:13 UTC
Labels: bug

**Comment by myspaghetti** [comment] 2020-07-20 15:40
Script version `0.96.0` defaults to sending one scancode at a time, so this issue is workaround-ed.
