### ISSUE TITLE
 line 1076: -: syntax error

### ISSUE THREAD

**Issue by englandgreen** [myspaghetti/macos-guest-virtualbox#169] opened 2020-03-03 13:36 UTC
sh macos-guest-virtualbox.sh

macos-guest-virtualbox.sh: line 1076: -: syntax error: operand expected (error token is "-")

Specs:
GNU bash, version 5.0.16(1)-release (x86_64-apple-darwin19.3.0) - default shell
Homebrew 2.2.6
VirtualBox 6.1.4
Mac Pro 5,1
Catalina 10.15.3 (Dosdude1 Patch)
64Gb RAM
2 x 3.46 GHz 6-Core Intel Xeon
AMD Radeon HD 7950 3 GB

Logged in as an administrator. Have full read/write access to installation directory. Tried "sudo", same error.

**Comment by myspaghetti** [comment] 2020-03-03 13:45
macOS `/bin/bash` is bash 3. Make sure you run the script with `/path/to/bash5 macos-guest-virtualbox.sh`

You should have gotten the error message `macOS detected. Make sure the script is not running on the default /bin/bash which is version 3`

Duplicate of [issue 116](https://github.com/myspaghetti/macos-guest-virtualbox/issues/116)

**Closed by myspaghetti** 2020-03-03 13:45 UTC
Labels: duplicate

**Comment by myspaghetti** [comment] 2020-03-03 13:47
macOS `/bin/bash` is bash 3. Make sure you run the script with `/path/to/bash5 macos-guest-virtualbox.sh`

You should have gotten the error message `macOS detected. Make sure the script is not running on the default /bin/bash which is version 3`

Duplicate of [issue 116](https://github.com/myspaghetti/macos-guest-virtualbox/issues/116)

And for future reference, do not run scripts with elevated privileges unless you actually know why they require them and what they do with them. This script, and VirtualBox, do not require elevated privileges and running them with elevated privileges creates permissions issues.
