### ISSUE TITLE
Installation on AMD system

### ISSUE THREAD

**Issue by Najihel** [myspaghetti/macos-guest-virtualbox#183] opened 2020-04-02 19:17 UTC
Hello,

To permit the installation in an AMD system you have to modify the CPU profile.

For example :

```
cd "C:\Program Files\Oracle\VirtualBox\" 
VBoxManage.exe modifyvm macOS --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff 
VBoxManage setextradata macOS "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "iMac11,3" 
VBoxManage setextradata macOS "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0" 
VBoxManage setextradata macOS "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Iloveapple" 
VBoxManage setextradata macOS "VBoxInternal/Devices/smc/0/Config/DeviceKey" "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc" 
VBoxManage setextradata macOS "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1
VBoxManage modifyvm macOS --cpu-profile "Intel Core i7-6700K"
```

Source : [removed link to bad tutorial]

**Comment by myspaghetti** [comment] 2020-04-03 01:22
Duplicate of #8 , which is pinned and linked from the release page.

**Closed by myspaghetti** 2020-04-03 01:22 UTC
Labels: duplicate

**Comment by MrTob** [comment] 2020-09-27 11:22
didnt't work for me

Specs:
Win 10
AMD Ryzen 7 3700X
24 GB Ram
GeForce GTX 1060
