### ISSUE TITLE
Please run this script on BASH 4.0 or higher.

### ISSUE THREAD

**Issue by rezaabedian** [myspaghetti/macos-guest-virtualbox#130] opened 2019-11-24 12:11 UTC
I am getting the following error:

> ./macos-guest-virtualbox.sh 
./macos-guest-virtualbox.sh: line 577: -: syntax error: operand expected (error token is "-")
Please run this script on BASH 4.0 or higher.

This is after I have upgraded my default version of bash on mac os to:
` bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`

**Comment by myspaghetti** [comment] 2019-11-24 12:19
macOS `/bin/bash` is bash 3. Make sure you run the script with `/path/to/bash5 macos-guest-virtualbox.sh`

Duplicate of [issue 116](https://github.com/myspaghetti/macos-guest-virtualbox/issues/116)

**Closed by myspaghetti** 2019-11-24 12:19 UTC
Labels: duplicate
