### ISSUE TITLE
Stuck after `Initialized /dev/rdisk4 as a 10 MB case-insensitive HFS Plus volume` on restart

### ISSUE THREAD

**Issue by Animenosekai** [myspaghetti/macos-guest-virtualbox#203] opened 2020-05-08 15:49 UTC
I have installed a guest macOS on my iMac to test my apps on a clean machine (check if there are dependencies missing with my installation file).
I succeeded with the installation, at least that was what I thought when I saw the script saying that it was done.
After finishing Preparing and doing it stuff it restarted but now I'm stuck after the `Initialized /dev/rdisk4 as a 10 MB case-insensitive HFS Plus volume` on booting.

Result from `./macos-guest-virtualbox.sh troubleshoot` :
[troubleshoot.txt](https://github.com/myspaghetti/macos-guest-virtualbox/files/4600024/troubleshoot.txt)

The messages when starting the machine:
<img width="1517" alt="Capture d’écran 2020-05-08 à 17 40 09" src="https://user-images.githubusercontent.com/40539549/81422767-bac4e380-9153-11ea-98c2-beb6b454b8f8.png">

**Comment by Animenosekai** [comment] 2020-05-08 21:21
Just to clarify, I was trying to install Catalina

**Comment by Animenosekai** [comment] 2020-05-08 21:23
Well, I completely deleted Catalina and retried but still doesn't work, so I'm going to try installing Mojave (little sad because it takes lots of time downloading InstallESD and making the file into multiple part)

**Comment by myspaghetti** [comment] 2020-05-08 23:08
Thanks for the bug report! This one's pretty interesting since the installer finishes but the OS doesn't boot! Investigating.

**Comment by myspaghetti** [comment] 2020-05-08 23:22
According to the log there's nothing wrong with your VirtualBox configuration or your downloaded files so everything is working... except the macOS guest. Unfortunately I'm going to have to mark this non-script. I'll try to reproduce it but I don't have an iMac handy, and everything works on my MacBook Pro.

You could try changing the storage controller to NVMe (PCIe). This will make VirtualBox fail to recognize `boot.efi` and allow you to manually load it with `fs1:\System\Library\CoreServices\boot.efi` and if it still doesn't boot you can change the boot NVRAM variables around.

I'll try to reproduce the issue if I get a chance. I'm closing the issue but please reopen it if you or anybody else has new information.

**Closed by myspaghetti** 2020-05-08 23:22 UTC
Labels: bug
