### ISSUE TITLE
Recovery Mode

### ISSUE THREAD

**Issue by dadons7** [myspaghetti/macos-guest-virtualbox#95] opened 2019-09-02 00:15 UTC
Thank you for creating this awesome script! *****

Using in VirtualBox 6.0.10 - Linux Host - PC

Everything working - need to get in Recovery Mode to disable SIP

Command-R or Command-alt-R do not work

I googled and I am lost - any suggestions would be greatly appreciated

**Comment by myspaghetti** [comment] 2019-09-02 01:34
(duplicate of [issue 89](https://github.com/myspaghetti/macos-guest-virtualbox/issues/89))

Disable SIP with the following VirtualBox commands on the host:
```
VBoxManage setextradata "${vmname}" "VBoxInternal/Devices/efi/0/LUN#0/Config/Vars/0003/Uuid" "7C436110-AB2A-4BBB-A880-FE41995C9F82"
VBoxManage setextradata "${vmname}" "VBoxInternal/Devices/efi/0/LUN#0/Config/Vars/0003/Name" "csr-active-config"
VBoxManage setextradata "${vmname}" "VBoxInternal/Devices/efi/0/LUN#0/Config/Vars/0003/Value" "bytes:dw=="
```

**Closed by myspaghetti** 2019-09-02 01:34 UTC

**Comment by Brutiz** [comment] 2020-12-18 06:59
i ran these commands, and now my vm wont boot with an error message that says `Can't attach Nvram Storage driver (VERR_PDM_CFG_MISSING_DRIVER_NAME).`
any way to fix this without deleting the stuff i had on the vm before this
