### ISSUE TITLE
Won't boot

### ISSUE THREAD

**Issue by brauliobo** [myspaghetti/macos-guest-virtualbox#160] opened 2020-02-04 23:10 UTC
all the script suceed, then when booting it get stuck on `End RandomSeed`

![image](https://user-images.githubusercontent.com/41740/73795841-6132ce80-478a-11ea-976b-d8068dd5dd20.png)

**Comment by danieltomasz** [comment] 2020-02-05 00:19
Which system do you try to boot? There are problems from 10.15.2  and above

**Comment by myspaghetti** [comment] 2020-02-05 03:18
Duplicate of [issue 8](https://github.com/myspaghetti/macos-guest-virtualbox/issues/8)

**Closed by myspaghetti** 2020-02-05 03:18 UTC
Labels: duplicate

**Comment by brauliobo** [comment] 2020-02-05 12:56
@danieltomasz here it is the install log

```
~/macos-guest-virtualbox ❯❯❯ ./macos-guest-virtualbox.sh                                                                                                     master

                Semi-automatic installer of macOS on VirtualBox
-------------------------------------------------------------------------------

This script installs only open-source software and unmodified Apple binaries.

The script checks for dependencies and will prompt to install them if unmet.

For iCloud and iMessage connectivity, the script needs to be edited with genuine
or genuine-like Apple parameters. macOS will work without these parameters, but
Apple-connected apps will not.

The installation requires about 40GB of available storage, 25GB for
temporary installation files and 15GB for the virtual machine's dynamically
allocated storage disk image.

The script can be resumed, as described when running the following command:
  ./macos-guest-virtualbox.sh documentation | less -R

Press enter to review the script settings.

vmname="macOS"                   # name of the VirtualBox virtual machine
macOS_release_name="Mojave"      # install "HighSierra" "Mojave" or "Catalina"
storagesize=80000                # VM disk image size in MB. minimum 22000
cpucount=2                       # VM CPU cores, minimum 2
memorysize=4096                  # VM RAM in MB, minimum 2048
gpuvram=128                      # VM video RAM in MB, minimum 34, maximum 128
resolution="1280x800"            # VM display resolution

These values may be customized by editing them at the top of the script file.

Press enter to continue, CTRL-C to exit.

Mojave selected to be downloaded and installed

stage: prompt_delete_existing_vm

stage: create_vm

stage: prepare_macos_installation_files

Downloading Apple macOS Mojave software update catalog
Mojave_sucatalog                         100%[==================================================================================>]   6,08M  8,06MB/s    em 0,8s
Trying to find macOS Mojave InstallAssistant download URL
Mojave_sucatalog_00_InstallAssistantAuto 100%[==================================================================================>]  39,98K  --.-KB/s    em 0,09s
Mojave_sucatalog_01_InstallAssistantAuto 100%[==================================================================================>]     969  --.-KB/s    em 0s
Mojave_sucatalog_02_InstallAssistantAuto 100%[==================================================================================>]  39,90K  --.-KB/s    em 0,08s
Found download URL: http://swcdn.apple.com/content/downloads/34/54/041-88800-A_HLMBDM42FL/anrmoj880qkj0lbybqm0c3830p70nawjrv/

Downloading macOS installation files from swcdn.apple.com
Mojave_BaseSystem.chunklist              100%[==================================================================================>]   1,94K  --.-KB/s    em 0s
Mojave_InstallInfo.plist                 100%[==================================================================================>]   1,55K  --.-KB/s    em 0s
Mojave_AppleDiagnostics.dmg              100%[==================================================================================>]   2,87M  4,86MB/s    em 0,6s
Mojave_AppleDiagnostics.chunklist        100%[==================================================================================>]     328  --.-KB/s    em 0s
Mojave_BaseSystem.dmg                    100%[==================================================================================>] 467,18M  10,6MB/s    em 38s
Mojave_InstallESDDmg.pkg                 100%[==================================================================================>]   5,15G  13,0MB/s    em 7m 16s

Splitting the several-GB InstallESDDmg.pkg into 1GB parts because
VirtualBox hasn't implemented UDF/HFS VISO support yet and macOS
doesn't support ISO 9660 Level 3 with files larger than 2GB.
criando arquivo 'Mojave_InstallESD.part00'
criando arquivo 'Mojave_InstallESD.part01'
criando arquivo 'Mojave_InstallESD.part02'
criando arquivo 'Mojave_InstallESD.part03'
criando arquivo 'Mojave_InstallESD.part04'
criando arquivo 'Mojave_InstallESD.part05'

Downloading open-source APFS EFI drivers used for VirtualBox 6.0 and 5.2
...even though that's not the version of VirtualBox that's been detected.
AppleSupport-v2.0.4-RELEASE.zip          100%[==================================================================================>]  42,20K  --.-KB/s    em 0,1s
Archive:  AppleSupport-v2.0.4-RELEASE.zip
  inflating: ApfsDriverLoader.efi
  inflating: AppleImageLoader.efi
  inflating: AppleUiSupport.efi

stage: create_nvram_files

stage: create_macos_installation_files_viso
Creating EFI startup script

Creating VirtualBox 6 virtual ISO containing the
installation files from swcdn.apple.com


stage: create_basesystem_vdi
Converting to BaseSystem.dmg to BaseSystem.img

dmg2img v1.6.7 (c) vu1tur (to@vu1tur.eu.org)

Mojave_BaseSystem.dmg --> Mojave_BaseSystem.img


decompressing:
opening partition 0 ...             100.00%  ok
opening partition 1 ...             100.00%  ok
opening partition 2 ...             100.00%  ok
opening partition 3 ...             100.00%  ok
opening partition 4 ...             100.00%  ok
opening partition 5 ...             100.00%  ok
opening partition 6 ...             100.00%  ok
opening partition 7 ...             100.00%  ok

Archive successfully decompressed as Mojave_BaseSystem.img
Converting from raw image file="Mojave_BaseSystem.img" to file="Mojave_BaseSystem.vdi"...
Creating dynamic image with size 2147426304 bytes (2048MB)...

stage: create_target_vdi
Creating macOS target system virtual disk image.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Medium created. UUID: 08fec801-d1c1-4eca-8335-fe5afbf0c96a

stage: create_install_vdi
Creating Mojave installation media virtual disk image.
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Medium created. UUID: 68950b6e-9df1-437e-8f2c-d4f0f4945529

stage: configure_vm

stage: populate_virtual_disks
Starting virtual machine macOS. This should take a couple of minutes.

Press enter when the Language window is ready.

Press enter when the macOS Utilities window is ready.^C
```

**Comment by brauliobo** [comment] 2020-02-05 13:01
also on Ryzen here, `VBoxManage modifyvm "macOS" --cpu-profile "Intel Xeon X5482 3.20GHz"` seems to make the boot start

**Comment by john1726** [comment] 2021-02-13 00:59
My installation gets to:

`Press enter when the Language window is ready.`

When I try this command:

`VBoxManage modifyvm "macOS" --cpu-profile "Intel Core i9-10900F 2.80GHz"`

I end up receiving this error. 

```
Failed to open a session for the virtual machine macOS.

Info on guest CPU 'Intel Core i9-10900F 2.80GHz' could not be found. Please, select a different CPU. (VERR_CPUM_DB_CPU_NOT_FOUND).

Result Code: E_FAIL (0x80004005)
Component: ConsoleWrap
Interface: IConsole {872da645-4a9b-1727-bee2-5585105b9eed}
```

 Does anyone have any suggestions?  TIA.
